### ISSUE TITLE
Autocomplete moduleID when using command testModule

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio-deprecated#5]
Is there any possibility to autocomplete the moduleId when using ```testModule <moduleID>``` command in order to help user using this command?

**Comment by gabrielhruiz** [comment]
I think this would be a new feature. IDEAS console is a mashup of GCLI console of mozilla that provide autocomplete the registered commands, but not the commands parameters.

**Comment by feserafim** [comment]
Ok. We will keep this issue open for a future enhancement possibility until we have an feature branch that implements it.
Thanks for answering :+1:

**Comment by juanlu91** [comment]
Currently, autocomplete is not implemented in gcli console. It would be a nice feature for the future.

P.S.: [Command metadata](https://github.com/joewalker/gcli/blob/master/docs/writing-commands.md#command-metadata)

**Comment by juanlu91** [comment]
This issue was moved to isa-group/ideas-studio#4

**Comment by feserafim** [comment]
This issue was moved to isa-group/ideas-studio#5
