### ISSUE TITLE
Uploading a file into a file

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-studio-deprecated#6]
If you have selected a file on IDEAS file tree and you try to upload a file, the uploaded file will be inside the selected file. The selected file interface will act as a folder.
Also, the uploaded file won't be saved anywhere. You can check that by refreshing the page.

**Comment by gabrielhruiz** [comment]
Sorry, I can't work in the said bug, but I think that this is the fix:

File: src/webapp/js/dynatree/projectsTree.js, 
line: 248 & 152, 
event: onDrop.

The function move the dynatree elements but not check that the destiny folder was a real folder. In fact, has to be consistency between dynatree client and workspace manager (server).

**Comment by feserafim** [comment]
This issue was moved to isa-group/ideas-studio#6
